name: f4r-bulk-recycling-model
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - networkx
  - notebook
  - nbstripout
  - matplotlib
  - xarray
  - netCDF4
  - geopandas
  - cartopy
  - dask
  - rioxarray
prefix: /home/sam/miniconda3/envs/f4r-bulk-recycling-model
